version: "96.1251"

services:
  shuna96:
    container_name: luteg96-shuna
    build:
      context: .
      dockerfile: Dockerfile
    command: bash start.sh
    restart: on-failure
    environment:
      - CONFIG_FILE_URL=
